services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  app:
    build: .
    command: >
      sh -c "python manage.py wait_for_db && \
             python manage.py makemigrations && \
             python manage.py migrate && \
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - my_media:/files/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - IN_DOCKER=true
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  my_media:
