# Generated by Django 5.2.6 on 2025-09-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_amenity_roomtype_hotel_rating_room"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="photos",
            field=models.ImageField(
                blank=True, null=True, upload_to="hotels/"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="photos",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
    ]
