# Generated by Django 5.2.6 on 2025-09-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_hotel_photos_room_photos"),
    ]
    
    operations = [
        migrations.AlterField(
            model_name="room",
            name="max_guests",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
