# Generated by Django 5.2.6 on 2025-09-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]
    
    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("CONFIRMED", "CONFIRMED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
